version: '3.7'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - typebot_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    networks:
      - typebot

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typebot-builder.rule=Host(`typebot.fluxosmm.com`)"
      - "traefik.http.routers.typebot-builder.entrypoints=web,websecure"
      - "traefik.http.routers.typebot-builder.tls.certresolver=leresolver"
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.fluxosmm.com
      - NEXT_PUBLIC_VIEWER_URL=https://chat.fluxosmm.com
      - ENCRYPTION_SECRET=K+Bar660Ofaec7v1jHC25tAn3l2b7c81
      - ADMIN_EMAIL=contato@fluxosmm.com
      - DISABLE_SIGNUP=false
      - SMTP_AUTH_DISABLED=false
      - SMTP_SECURE=true
      - SMTP_HOST=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_USERNAME=contato@fluxosmm.com
      - SMTP_PASSWORD=Intruso99@
      - NEXT_PUBLIC_SMTP_FROM=contato@fluxosmm.com
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.fluxosmm.com
      - typebot

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typebot-viewer.rule=Host(`chat.fluxosmm.com`)"
      - "traefik.http.routers.typebot-viewer.entrypoints=web,websecure"
      - "traefik.http.routers.typebot-viewer.tls.certresolver=leresolver"
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.fluxosmm.com
      - NEXT_PUBLIC_VIEWER_URL=https://chat.fluxosmm.com
      - ENCRYPTION_SECRET=K+Bar660Ofaec7v1jHC25tAn3l2b7c81
      - SMTP_HOST=smtp.hostinger.com
      - NEXT_PUBLIC_SMTP_FROM=contato@fluxosmm.com
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.seudominio.com 
    networks:
      - typebot

  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - typebot

  minio:
    image: minio/minio
    restart: always
    command: server /data
    ports:
      - '9000:9000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`storage.fluxosmm.com`)" 
      - "traefik.http.routers.minio.entrypoints=web,websecure"
      - "traefik.http.routers.minio.tls.certresolver=leresolver"
    environment:
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: minio123 
    volumes:
      - typebot_s3_data:/data
    networks:
      - typebot

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
    networks:
      - typebot

volumes:
  typebot_db_data:
  typebot_s3_data:

networks:
  typebot:
    external: true
