version: '3.3'
services:
  caddy-gen:
    image: 'wemakeservices/caddy-gen:latest'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - '81:80'
      - '8443:443'
    depends_on:
      - typebot-builder
      - typebot-viewer
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    labels:
      virtual.host: 'https://typebot.fluxosmm.com'
      virtual.port: '3000'
      virtual.tls-email: 'contato@fluxosmm.com'
    image: baptistearno/typebot-builder:latest
    restart: always
    ports:
      - '3001:3000'
    depends_on:
      - typebot-db
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.fluxosmm.com
      - NEXT_PUBLIC_VIEWER_URL=https://chat.fluxosmm.com
      - ENCRYPTION_SECRET=K+Bar660Ofaec7v1jHC25tAn3l2b7c81
      - ADMIN_EMAIL=contato@fluxosmm.com
      - DISABLE_SIGNUP=false
      - SMTP_AUTH_DISABLED=false
      - SMTP_SECURE=true
      - SMTP_HOST=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_USERNAME=contato@fluxosmm.com
      - SMTP_PASSWORD=Intruso99@
      - NEXT_PUBLIC_SMTP_FROM=contato@fluxosmm.com
      - S3_ACCESS_KEY=minio 
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.fluxosmm.com
  typebot-viewer:
    labels:
      virtual.host: 'chat.fluxosmm.com'
      virtual.port: '3000'
      virtual.tls-email: 'contato@fluxosmm.com'
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '3002:3000'
    
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.fluxosmm.com
      - NEXT_PUBLIC_VIEWER_URL=https://chat.fluxosmm.com
      - SMTP_HOST=smtp.hostinger.com
      - NEXT_PUBLIC_SMTP_FROM=contato@fluxosmm.com
      - S3_ACCESS_KEY=minio 
      - S3_SECRET_KEY=minio123 
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.fluxosmm.com
  mail:
    image: bytemark/smtp
    restart: always
  minio:
    labels:
      virtual.host: 'storage.fluxosmm.com'
      virtual.port: '9000'
      virtual.tls-email: 'contato@fluxosmm.com'
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: minio123 
    volumes:
      - s3_data:/data
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
volumes:
  db_data:
  s3_data:
  caddy-certificates:
    driver: local
